name: "Sample React CI Pipeline/Workflow"

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch
      - master  # Triggers on pushes to the master branch
  pull_request:
    branches:
      - main  # Triggers on pull requests targeting the main branch
      - master  # Triggers on pull requests targeting the master branch

jobs:
  build-test:
    runs-on: ubuntu-latest  # Specifies the OS for the job

    steps:
      # Step 1: Checkout the code
      - name: "Checkout repository"
        uses: actions/checkout@v2  # Check out the repository

      # Step 2: Set up Node.js
      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '21'  # Specify the Node.js version

      # Step 3: Check Node.js version
      - name: "Check Node.js version"
        run: node --version  # Run to verify Node.js installation

      # Step 4: Install dependencies
      - name: "Install dependencies"
        run: npm install  # Install npm packages

      # Step 5: List down the directories
      - name: "List down the directories"
        run: ls  # List directories and files

      # Step 6: Run tests
      - name: "Run tests"
        run: npm test  # Execute tests

      # Step 7: Run build
      - name: "Run build"
        run: npm run build  # Build the React application
